{% set version = "12.4.1" %}

package:
  name: cuda-libraries
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_documentation/LICENSE.txt
  sha256: e2c71babfd18a8e69542dd7e9ca018f9caa438094001a58e6bc4d8c999bf0d07

build:
  number: 1
  skip: true  # [osx]

requirements:
  run:
    - cuda-cudart 12.4.127
    - cuda-nvrtc 12.4.127
    - cuda-opencl 12.4.127    # [linux64 or win]
    - libcublas 12.4.5.8
    - libcufft 11.2.1.3 
    - libcufile 1.9.1.3       # [linux64 or aarch64]
    - libcurand 10.3.5.147
    - libcusolver 11.6.1.9
    - libcusparse 12.3.1.170
    - libnpp 12.2.5.30
    - libnvfatbin 12.4.127
    - libnvjitlink 12.4.127
    - libnvjpeg 12.3.1.117

test:
  commands:
    - exit 0

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE.txt
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Meta-package containing all available library runtime packages.
  description: |
    Meta-package containing all available library runtime packages.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
