{% set version = "12.0.0" %}

package:
  name: cuda-libraries
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_documentation/LICENSE.txt
  sha256: 5db25d4fd138013b563f9a3d1d87f7de7df1dac014fd4cccdfbb3435a5cff761

build:
  number: 1
  skip: true  # [osx or win]

requirements:
  run:
    - cuda-cudart 12.0.107
    - cuda-nvrtc 12.0.76
    - cuda-opencl 12.0.76  # [linux64 or win]
    - libcublas 12.0.1.189
    - libcufft 11.0.0.21 
    - libcufile 1.5.0.59  # [linux64]
    - libcurand 10.3.1.50
    - libcusolver 11.4.2.57
    - libcusparse 12.0.0.76
    - libnpp 12.0.0.30
    - libnvjitlink 12.0.76
    - libnvjpeg 12.0.0.28

test:
  commands:
    - exit 0

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE.txt
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Meta-package containing all available library runtime packages.
  description: |
    Meta-package containing all available library runtime packages.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - adibbley
