{% set version = "12.4.0" %}

package:
  name: cuda-libraries
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_documentation/LICENSE.txt
  sha256: 5db25d4fd138013b563f9a3d1d87f7de7df1dac014fd4cccdfbb3435a5cff761

build:
  number: 0
  skip: true  # [osx]

requirements:
  run:
    - cuda-cudart 12.4.99
    - cuda-nvrtc 12.4.99
    - cuda-opencl 12.4.99    # [linux64 or win]
    - libcublas 12.4.2.65
    - libcufft 11.2.0.44 
    - libcufile 1.9.0.20       # [linux64 or aarch64]
    - libcurand 10.3.5.119
    - libcusolver 11.6.0.99
    - libcusparse 12.3.0.142
    - libnpp 12.2.5.2
    - libnvfatbin 12.4.99
    - libnvjitlink 12.4.99
    - libnvjpeg 12.3.1.89

test:
  commands:
    - exit 0

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE.txt
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Meta-package containing all available library runtime packages.
  description: |
    Meta-package containing all available library runtime packages.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
